image:
#- Visual Studio 2013
#- Visual Studio 2015
- Visual Studio 2017
- Visual Studio 2017 Preview

platform:
- x64
- x86
- Any CPU

configuration:
 - Debug
 - RelWithDebInfo
 - Release

version: '{branch}-{build}'

init:
- echo %NUMBER_OF_PROCESSORS%
- echo %PLATFORM%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- set arch=
- if "%PLATFORM%"=="x64" ( set arch= Win64)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" (set generator=Visual Studio 12 2013%arch%)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (set generator=Visual Studio 14 2015%arch%)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (set generator=Visual Studio 15 2017%arch%)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017 Preview" (set generator=Visual Studio 15 2017%arch%)
- echo %generator%

install:
  - choco install -y dokany --installargs ADDLOCAL=DokanDevFeature,DokanLibBFeature,DokanPDBFeature
  - cmake --version

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -G "%generator%" -DBUILD_TESTING=on -DBOOST_ROOT=C:\Libraries\boost_1_65_1 -DDOKAN_PATH="C:\Program Files\Dokan\DokanLibrary-1.1.0"
  # TODO Make build parallel
  - cmd: cmake --build . --config %CONFIGURATION%
  - cmd: .\test\gitversion\%CONFIGURATION%\gitversion-test.exe
  - cmd: cd .\test\cpp-utils\%CONFIGURATION%\ && .\cpp-utils-test.exe && cd ..\..\..
  #- cmd: .\test\fspp\%CONFIGURATION%\fspp-test.exe
  - cmd: .\test\parallelaccessstore\%CONFIGURATION%\parallelaccessstore-test.exe
  - cmd: .\test\blockstore\%CONFIGURATION%\blockstore-test.exe
  - cmd: .\test\blobstore\%CONFIGURATION%\blobstore-test.exe
  - cmd: .\test\cryfs\%CONFIGURATION%\cryfs-test.exe
  #- cmd: .\test\cryfs-cli\%CONFIGURATION%\cryfs-cli-test.exe
  #- cmd: cpack --verbose -G WIX

on_failure:
  - cmd: type C:\projects\cryfs\build\_CPack_Packages\win64\WIX\wix.log

artifacts:
 - path: build/cryfs-*.msi
   name: CryFS
