version: 0.9.{build}
 
install:
  - ps: wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-win32-x86.zip -OutFile cmake.zip
  - cmd: echo "Unzipping cmake..."
  - cmd: 7z x cmake.zip -o"C:\Program Files (x86)\" -y > nul
  - cmd: set PATH=%PATH:CMake 2.8\bin=%;C:\Program Files (x86)\cmake-3.0.2-win32-x86\bin
  - cmd: cmake --version
  - cmd: echo "Downloading biicode..."
  - ps: wget http://www.biicode.com/downloads/latest/win -OutFile bii-win.exe
  - cmd: bii-win.exe /VERYSILENT
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii
  - cmd: bii -v
  - cmd: del bii-win.exe
  - cmd: del cmake.zip
 
before_build:
  - cmd: bii init -L
    # copy files and folders
  - cmd: xcopy "%APPVEYOR_BUILD_FOLDER%" blocks\%block_user%\%block_name%\ /e
  - cmd: bii configure -G "Visual Studio 12"
 
build_script:
  - cmd: bii build
 
test_script:
  - cmd: cd bin
  - cmd: amalulla_cpp-expression-parser_test-shunting-yard.exe

environment:
  block_user:
    "messmer"
  block_name:
    "blockstore"

