image: Visual Studio 2017
version: '{branch}-{build}'

platform:
  - x64
#  TODO: For x86, we also need to change the cmake generator below and possibly the dokan installation
#  - x86
#  - Any CPU

configuration:
  - Debug
  - RelWithDebInfo

install:
  - choco install -y dokany --installargs ADDLOCAL=DokanDevFeature,DokanLibBFeature,DokanPDBFeature
  - cmake --version

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmake .. -G "Visual Studio 15 2017 Win64" -DBUILD_TESTING=on -DBOOST_ROOT=C:\Libraries\boost_1_65_1 -DDOKAN_LIB_PATH="C:\Program Files\Dokan\DokanLibrary-1.1.0"
  # TODO Make build parallel
  - cmd: cmake --build . --config %CONFIGURATION%
  - cmd: .\test\gitversion\%CONFIGURATION%\gitversion-test.exe
  - cmd: cd .\test\cpp-utils\%CONFIGURATION%\ && .\cpp-utils-test.exe && cd ..\..\..
  #- cmd: .\test\fspp\%CONFIGURATION%\fspp-test.exe
  - cmd: .\test\parallelaccessstore\%CONFIGURATION%\parallelaccessstore-test.exe
  - cmd: .\test\blockstore\%CONFIGURATION%\blockstore-test.exe
  - cmd: .\test\blobstore\%CONFIGURATION%\blobstore-test.exe
  - cmd: .\test\cryfs\%CONFIGURATION%\cryfs-test.exe
  #- cmd: .\test\cryfs-cli\%CONFIGURATION%\cryfs-cli-test.exe
