image:
- Visual Studio 2019
#- Visual Studio 2019 Preview

platform:
- x64
- x86
#- Any CPU

configuration:
 - Debug
 - RelWithDebInfo
 - Release

version: '{branch}-{build}'

init:
- echo %NUMBER_OF_PROCESSORS%
- echo %PLATFORM%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- set arch=32
- if "%PLATFORM%"=="x64" ( set arch=64)
- set VisualStudioVersion=2019
- if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2019 Preview" ( set VisualStudioVersion=Preview)
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\%VisualStudioVersion%\Community\VC\Auxiliary\Build\vcvars%arch%.bat"

install:
  - choco install -y dokany --version 1.2.1.2000 --installargs INSTALLDEVFILES=1
  - pip install conan
  - conan --version
  - cmake --version
  - conan profile new default --detect
  # note: Conan misdetects our x86 CI platform as x64, fix that
  - if "%PLATFORM%"=="x86" ( conan profile update settings.arch=x86 default )
  - if "%PLATFORM%"=="x86" ( conan profile update settings.arch_build=x86 default )

build_script:
  - cmd: mkdir build
  - cmd: cd build
  # note: The cmake+ninja workflow requires us to set build type in both cmake commands ('cmake' and 'cmake --build'), otherwise the cryfs.exe will depend on debug versions of the visual studio c++ runtime (i.e. msvcp140d.dll)
  # note: The CMAKE_SYSTEM_VERSION variable is set to 10.0.18362.0 because as of this writing, appveyor uses 10.0.17763.0 and that has a bug, see https://developercommunity.visualstudio.com/content/problem/343296/sdk-and-experimentalpreprocessor.html
  - cmd: cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBUILD_TESTING=on -DDOKAN_PATH="C:/Program Files/Dokan/DokanLibrary-1.2.1" -DCMAKE_SYSTEM_VERSION="10.0.18362.0"
  - cmd: cmake --build . --config %CONFIGURATION%
  - cmd: .\bin\gitversion-test.exe
  # cpp-utils-test disables ThreadDebuggingTest_ThreadName.*_thenIsCorrect because the appveyor image is too old to support the API needed for that
  - cmd: .\bin\cpp-utils-test.exe --gtest_filter=-ThreadDebuggingTest_ThreadName.*_thenIsCorrect
  #- cmd: .\bin\fspp-test.exe
  - cmd: .\bin\parallelaccessstore-test.exe
  - cmd: .\bin\blockstore-test.exe
  - cmd: .\bin\blobstore-test.exe
  - cmd: .\bin\cryfs-test.exe
  #- cmd: .\bin\cryfs-cli-test.exe

  - cmd: cpack -C %CONFIGURATION% --verbose -G WIX

on_failure:
  - cmd: type C:\projects\cryfs\build\_CPack_Packages\win64\WIX\wix.log

artifacts:
 - path: build/cryfs-*.msi
   name: CryFS
