[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Sebastian Messmer <messmer@cryfs.org>"]
edition = "2021"
rust-version = "1.67"
homepage = "https://www.cryfs.org"
repository = "https://github.com/cryfs/cryfs"
license = "LGPL-3.0-or-later"
readme = "README.md"
version = "0.11.0"
# TODO Set categories, keywords, documentation, description (and then make sure to link the crates/*/Cargo.toml to it)
# TODO look at whether we want to add [badges], see https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section

[workspace.dependencies]
# TODO Go through the dependencies and check if there are any default-features we don't need and can disable
aead = "^0.5.2"
aes-gcm = "^0.10.2"
anyhow = "^1.0.71"
assert_cmd = "^2.0.11"
async-recursion = "^1.0.4"
async-trait = "^0.1.68"
base64 = "^0.21.2"
binary-layout = "^3.1.3"
binrw = "^0.11.2"
chacha20poly1305 = "^0.10.1"
clap = "^4.3.4"
common_macros = "^0.1.1"
conv = "^0.3.3"
criterion = "^0.5.1"
derive_more = "^0.99.17"
dialoguer = "^0.10.4"
dirs = "^5.0.1"
divrem = "^1.0.0"
env_logger = "^0.10.0"
envtestkit = "^1.1.2"
errno = "^0.3.1"
escargot = "^0.5.7"
fuse_mt = "^0.6.0"
fuse_mt_fuser = {package = "fuser", version = "^0.11.0"}
futures = "^0.3.28"
generic-array = "^0.14.7"
generic-tests = "^0.1.2"
git2version = "^0.3.0"
hex = "^0.4.3"
iter-chunks = "^0.1.3"
itertools = "^0.10.5"
konst = "^0.3.5"
lazy_static = "^1.4.0"
libc = "^0.2.146"
lockable = "^0.0.6"
log = "^0.4.19"
lzzzz = "^1.0.4"
maybe-owned = "^0.3.4"
mockall = "^0.11.4"
nix = "^0.26.2"
openssl = "^0.10.54"
path-absolutize = "^3.1.0"
pathdiff = "^0.2.1"
predicates = "^3.0.3"
rand = "^0.8.5"
rayon = "^1.7.0"
region = "^3.0.0"
rpassword = "^7.2"
rstest = "^0.17.0"
rstest_reuse = "^0.5.0"
scrypt = {version = "^0.11.0", default-features = false}
serde = "^1.0.164"
serde_json = "^1.0.97"
serde_with = {version = "^3.0.0", features=["hex"]}
signal-hook = "^0.3.15"
sodiumoxide = "^0.2.7"
static_assertions = "^1.1.0"
sysinfo = "^0.29.2"
tempdir = "^0.3.7"
thiserror = "^1.0.40"
tokio = "^1.28.2"
tokio-stream = "^0.1.14"
tokio-util = "^0.7.8"
winapi = "^0.3.9"

[profile.release]
lto = "fat"
